CREATE TABLE public.inventory_classifications (
  id integer NOT NULL DEFAULT nextval('inventory_classifications_id_seq'::regclass),
  name character varying NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT inventory_classifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_items (
  id integer NOT NULL DEFAULT nextval('inventory_items_id_seq'::regclass),
  generic_name character varying NOT NULL,
  brand_name character varying,
  classification_id integer,
  category character varying,
  department character varying NOT NULL CHECK (department::text = ANY (ARRAY['medical'::character varying, 'dental'::character varying]::text[])),
  stock_quantity integer NOT NULL DEFAULT 0,
  unit_of_measurement character varying DEFAULT 'pcs'::character varying,
  expiration_date date,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'low_stock'::character varying, 'out_of_stock'::character varying, 'expired'::character varying, 'maintenance'::character varying, 'archived'::character varying]::text[])),
  minimum_stock_level integer DEFAULT 10,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_by integer,
  updated_by integer,
  code text,
  CONSTRAINT inventory_items_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_items_classification_id_fkey FOREIGN KEY (classification_id) REFERENCES public.inventory_classifications(id),
  CONSTRAINT inventory_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT inventory_items_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.user_activity (
  id integer NOT NULL DEFAULT nextval('user_activity_id_seq'::regclass),
  user_id integer,
  action character varying NOT NULL,
  category character varying,
  description text,
  timestamp timestamp with time zone DEFAULT now(),
  severity character varying DEFAULT 'info'::character varying CHECK (severity::text = ANY (ARRAY['info'::character varying, 'warning'::character varying, 'error'::character varying]::text[])),
  CONSTRAINT user_activity_pkey PRIMARY KEY (id),
  CONSTRAINT user_activity_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  username character varying NOT NULL UNIQUE,
  password character varying NOT NULL,
  role character varying DEFAULT 'admin'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'superadmin'::character varying]::text[])),
  first_name character varying,
  last_name character varying,
  phone character varying,
  department character varying,
  position character varying,
  employee_id character varying UNIQUE,
  license_number character varying,
  specialization text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  avatar_url text,
  bio text,
  gender character varying,
  emergency_contact_name character varying,
  emergency_contact_phone character varying,
  emergency_contact_relationship character varying,
  last_login timestamp with time zone,
  login_count integer DEFAULT 0,
  password_hash text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);